#!/bin/bash
# Tes backup.sh di home PALSU (tujuan drive palsu + ambil vault).  bash test_backup.sh
set -u
DIR="$(cd "$(dirname "$0")" && pwd)"
T=$(mktemp -d); trap 'rm -rf "$T"' EXIT
export AMNESIA_HOME="$T/home" AMNESIA_VOLUMES="$T/Volumes"
export AMNESIA_7Z="${AMNESIA_7Z:-$(command -v 7zz || command -v 7z)}"
mkdir -p "$T/home/.amnesia/vault" "$T/home/Keep" "$T/home/Documents" "$T/Volumes/SSD"
echo penting > "$T/home/Keep/a.txt"; echo kunci > "$T/home/.amnesia/vault/private.7z"; echo pub > "$T/home/.amnesia/vault/public.pem"
printf 'BACKUP_DEST=drive\nBACKUP_DRIVE=SSD\nBACKUP_FOLDERS=Keep,Documents\nBACKUP_VAULT=1\n' > "$T/home/.amnesia/settings.conf"
fail() { echo "FAILED: $*"; exit 1; }

echo "pw-backup-123" | bash "$DIR/backup.sh" >/dev/null 2>&1 || fail "backup to drive"
F=$(ls "$T/Volumes/SSD"/amnesia_backup_*.7z) || fail "backup file missing"
grep -q "OK:" "$T/home/.amnesia/backup.log" || fail "status log"
[ -f "$T/home/.amnesia/backup.ok" ] || fail "backup.ok marker"
grep -q "amnesia_backup_" "$T/home/.amnesia/backup_checksums.txt" || fail "checksum"
! grep -aq "penting" "$F" || fail "contents not encrypted"
[ -f "$T/home/.amnesia/backup.vault.ok" ] || fail "backup.vault.ok marker"
# vault ikut secara default (BACKUP_VAULT tidak diisi); BACKUP_VAULT=0 mematikannya
mv "$F" "$T/v1.7z"; F="$T/v1.7z"; rm -f "$T/home/.amnesia/backup.vault.ok"
printf 'BACKUP_DEST=drive\nBACKUP_DRIVE=SSD\nBACKUP_FOLDERS=Keep\n' > "$T/home/.amnesia/settings.conf"
echo "pw-backup-123" | bash "$DIR/backup.sh" >/dev/null 2>&1 || fail "backup with default vault"
D=$(ls "$T/Volumes/SSD"/amnesia_backup_*.7z); "$AMNESIA_7Z" l -p"pw-backup-123" "$D" | grep -q ".amnesia/vault/private.7z" || fail "vault not in backup by default"
[ -f "$T/home/.amnesia/backup.vault.ok" ] || fail "default vault marker"
rm -f "$D" "$T/home/.amnesia/backup.vault.ok"
printf 'BACKUP_DEST=drive\nBACKUP_DRIVE=SSD\nBACKUP_FOLDERS=Keep\nBACKUP_VAULT=0\n' > "$T/home/.amnesia/settings.conf"
echo "pw-backup-123" | bash "$DIR/backup.sh" >/dev/null 2>&1 || fail "backup without vault"
D=$(ls "$T/Volumes/SSD"/amnesia_backup_*.7z); "$AMNESIA_7Z" l -p"pw-backup-123" "$D" | grep -q ".amnesia/vault" && fail "BACKUP_VAULT=0 must leave the vault out"
[ ! -f "$T/home/.amnesia/backup.vault.ok" ] || fail "no vault marker without vault"
rm -f "$D"
# folder Keep custom lewat @keep (path lengkap di luar home juga bisa)
mkdir -p "$T/luar/Arsip"; echo rahasia-keep > "$T/luar/Arsip/k.txt"
printf 'BACKUP_DEST=drive\nBACKUP_DRIVE=SSD\nBACKUP_FOLDERS=@keep\nKEEP_DIR=%s\n' "$T/luar/Arsip" > "$T/home/.amnesia/settings.conf"
mv "$F" "$T/first.7z"; F="$T/first.7z"
echo "pw-backup-123" | bash "$DIR/backup.sh" >/dev/null 2>&1 || fail "backup custom keep folder"
G=$(ls "$T/Volumes/SSD"/amnesia_backup_*.7z) || fail "custom keep backup missing"
"$AMNESIA_7Z" l -p"pw-backup-123" "$G" | grep -q "Arsip/k.txt" || fail "custom keep folder not in backup"
printf 'BACKUP_DEST=drive\nBACKUP_DRIVE=SSD\nBACKUP_FOLDERS=Keep,Documents\nBACKUP_VAULT=1\n' > "$T/home/.amnesia/settings.conf"
echo "" | bash "$DIR/backup.sh" 2>/dev/null && fail "empty password must be refused"
sed -i.bak 's/BACKUP_DRIVE=SSD/BACKUP_DRIVE=TidakAda/' "$T/home/.amnesia/settings.conf"
echo "pw-backup-123" | bash "$DIR/backup.sh" 2>/dev/null && fail "missing drive must fail"
grep -q "FAILED" "$T/home/.amnesia/backup.log" || fail "failure log"

# Mac baru: vault belum ada -> ambil dari backup
rm -rf "$T/home/.amnesia/vault"
echo "salah-password" | bash "$DIR/backup.sh" --restore-vault "$F" 2>/dev/null && fail "wrong password must fail"
echo "pw-backup-123" | bash "$DIR/backup.sh" --restore-vault "$F" >/dev/null || fail "restore vault"
[ "$(cat "$T/home/.amnesia/vault/private.7z")" = kunci ] || fail "vault contents"
[ ! -e "$T/home/Keep/b" ] && [ ! -e "$T/home/.amnesia/Keep" ] || fail "only the vault is restored"
echo "pw-backup-123" | bash "$DIR/backup.sh" --restore-vault "$F" 2>/dev/null && fail "existing vault must not be overwritten"
# kemajuan & tombol Batal: berhenti rapi (kode 130), tidak ada file setengah jadi, backup.log tidak berubah
sed -i.bak 's/BACKUP_DRIVE=TidakAda/BACKUP_DRIVE=SSD/' "$T/home/.amnesia/settings.conf"
# v5.16: cek vault di file backup tanpa menyentuh vault yang ada
printf '{"apps": ["Chrome", "Claude"], "time": "2026-10-07 09:00"}' > "$T/home/.amnesia/vault/manifest.json"
echo "pw-backup-123" | bash "$DIR/backup.sh" >/dev/null 2>&1 || fail "backup for check-vault"
C=$(ls -t "$T/Volumes/SSD"/amnesia_backup_*.7z | head -1)
echo kunci-sekarang > "$T/home/.amnesia/vault/private.7z"
E=$(echo "salah-password" | bash "$DIR/backup.sh" --check-vault "$C" 2>&1 >/dev/null) && fail "check-vault wrong password must fail"
echo "$E" | grep -q "\[wrongpw\]" || fail "check-vault must say the password is wrong: $E"
R=$(echo "pw-backup-123" | bash "$DIR/backup.sh" --check-vault "$C" 2>/dev/null) || fail "check-vault"
echo "$R" | grep -q "^OK: VAULT .*2026-10-07 09:00|Chrome, Claude" || fail "check-vault info: $R"
[ "$(cat "$T/home/.amnesia/vault/private.7z")" = kunci-sekarang ] || fail "check-vault must not touch the vault"
rm -f "$C" "$T/home/.amnesia/vault/manifest.json"; echo kunci > "$T/home/.amnesia/vault/private.7z"
# v5.17: backup tanpa vault -> pesan "tidak berisi vault", bukan "password salah"
echo "BACKUP_VAULT=0" >> "$T/home/.amnesia/settings.conf"
echo "pw-backup-123" | bash "$DIR/backup.sh" >/dev/null 2>&1 || fail "backup without vault"
C=$(ls -t "$T/Volumes/SSD"/amnesia_backup_*.7z | head -1)
E=$(echo "pw-backup-123" | bash "$DIR/backup.sh" --check-vault "$C" 2>&1 >/dev/null) && fail "check-vault without vault must fail"
echo "$E" | grep -q "\[novault\]" || fail "check-vault must say there is no vault: $E"
rm -f "$C"; sed -i.bak '/^BACKUP_VAULT=0$/d' "$T/home/.amnesia/settings.conf"
grep -q "	backup	" "$T/home/.amnesia/history.log" || fail "history.log backup entry"

# v5.17: Pulihkan File ke lokasi asal (folder di home + folder di luar home), yang lama dipindah, tidak ditimpa
mkdir -p "$T/home/Keep/sub" "$T/luar/Proj"; echo b > "$T/home/Keep/sub/b.txt"; echo d > "$T/home/Documents/d.txt"; echo p > "$T/luar/Proj/p.txt"
printf 'BACKUP_DEST=drive\nBACKUP_DRIVE=SSD\nBACKUP_FOLDERS=Keep,Documents,%s\nBACKUP_VAULT=0\n' "$T/luar/Proj" > "$T/home/.amnesia/settings.conf"
echo "pw-backup-123" | bash "$DIR/backup.sh" >/dev/null 2>&1 || fail "backup for restore-files"
RB=$(ls -t "$T/Volumes/SSD"/amnesia_backup_*.7z | head -1); mv "$RB" "$T/rb.7z"; RB="$T/rb.7z"
"$AMNESIA_7Z" l -p"pw-backup-123" "$RB" | grep -q ".amnesia/backup-index.json" || fail "backup-index.json not in backup"
L=$(echo "pw-backup-123" | bash "$DIR/backup.sh" --list "$RB" 2>&1) || fail "list: $L"
echo "$L" | grep -q "^ITEM	Keep	d	[0-9]*	$T/home/Keep$" || fail "list Keep: $L"
echo "$L" | grep -q "^ITEM	Keep/a.txt	f	8	$T/home/Keep/a.txt$" || fail "list Keep/a.txt: $L"
echo "$L" | grep -q "^ITEM	Proj	d	[0-9]*	$T/luar/Proj$" || fail "list outside folder: $L"
echo "$L" | grep -q ".amnesia" && fail "list must hide .amnesia"
E=$(echo "salah" | bash "$DIR/backup.sh" --list "$RB" 2>&1 >/dev/null) && fail "list wrong password must fail"
echo "$E" | grep -q "\[wrongpw\]" || fail "list wrong password message: $E"
echo baru > "$T/home/Keep/a.txt"; rm -rf "$T/home/Documents/d.txt" "$T/luar/Proj"
O=$(echo "pw-backup-123" | bash "$DIR/backup.sh" --restore-files "$RB" Keep/a.txt Documents/d.txt Proj 2>&1) || fail "restore-files: $O"
echo "$O" | grep -q "^OK: RESTORED 3" || fail "restore-files count: $O"
[ "$(cat "$T/home/Keep/a.txt")" = penting ] || fail "Keep/a.txt not restored"
[ "$(cat "$T/home/Documents/d.txt")" = d ] || fail "Documents/d.txt not restored"
[ "$(cat "$T/luar/Proj/p.txt")" = p ] || fail "outside folder not restored to its original place"
[ "$(cat "$T/home/.amnesia/before-restore"/*/Keep/a.txt)" = baru ] || fail "existing file must be moved, not overwritten"
mkdir -p "$T/lain"
O=$(echo "pw-backup-123" | bash "$DIR/backup.sh" --restore-files "$RB" --to "$T/lain" Keep/sub 2>&1) || fail "restore-files --to: $O"
[ "$(cat "$T/lain/sub/b.txt")" = b ] || fail "restore to another folder"
echo "pw-backup-123" | bash "$DIR/backup.sh" --restore-files "$RB" .amnesia/vault >/dev/null 2>&1 && fail "restore-files must refuse .amnesia"
echo "pw-backup-123" | bash "$DIR/backup.sh" --restore-files "$RB" ../x >/dev/null 2>&1 && fail "restore-files must refuse .."
grep -q "	restorefiles	3" "$T/home/.amnesia/history.log" || fail "history restorefiles"
ls -d "$T/home"/.amnesia-restore.* >/dev/null 2>&1 && fail "temporary restore folder left behind"
rm -rf "$T/lain" "$T/home/.amnesia/before-restore" "$RB"
printf 'BACKUP_DEST=drive\nBACKUP_DRIVE=SSD\nBACKUP_FOLDERS=Keep,Documents\nBACKUP_VAULT=1\n' > "$T/home/.amnesia/settings.conf"

echo "pw-backup-123" | bash "$DIR/backup.sh" >/dev/null 2>"$T/prog" || fail "backup for progress"
grep -q "^PROGRESS [0-9]* compress 1/2" "$T/prog" || fail "compress progress lines"
grep -q "^PROGRESS 100 copy 2/2\|^PROGRESS [0-9]* copy 2/2" "$T/prog" || fail "copy progress lines"
rm -f "$T/Volumes/SSD"/*.7z
head -c 80000000 /dev/urandom > "$T/home/Documents/besar.bin"
cp "$T/home/.amnesia/backup.log" "$T/log.before"
( echo "pw-backup-123" | bash "$DIR/backup.sh" >/dev/null 2>"$T/cancel"; echo $? > "$T/cancel.rc" ) &
for _ in $(seq 1 100); do grep -q "^PROGRESS" "$T/cancel" 2>/dev/null && break; sleep 0.1; done
sleep 0.5
pkill -TERM -f "bash $DIR/backup.sh" || fail "backup not running"
wait
[ "$(cat "$T/cancel.rc")" = 130 ] || fail "cancel exit code $(cat "$T/cancel.rc")"
grep -q "^CANCELLED" "$T/cancel" || fail "cancel message"
sleep 0.5; pgrep -f "7z.*amnesia_backup" >/dev/null && fail "7z still running after cancel"
ls "$T/Volumes/SSD" | grep -q . && fail "half-written file left"
cmp -s "$T/home/.amnesia/backup.log" "$T/log.before" || fail "backup.log changed on cancel"
rm -f "$T/home/Documents/besar.bin"
echo "OK: all backup tests passed"
